# List of target hosts (IP addresses or host names) to ping.
targets:
  - 127.0.0.1
  - grafana.breeze-blocks.net
  - marius.breeze-blocks.net
  - media.breeze-blocks.net
  - nautobot.breeze-blocks.net
  - nextcloud.breeze-blocks.net
  - ns01.breeze-blocks.net
  - ns02.breeze-blocks.net
  - ns03.breeze-blocks.net

dns:
  # enforce a specific DNS server for host name lookups (optional,
  # defaults to system resolver)
  nameserver: 192.168.5.6

  # refresh interval for host name (optional)
  refresh: 2m45s

ping:
  interval: 2s # How often to ping a target?
  timeout: 3s # Timeout for a single ICMP Echo Request
  history-size: 42 # number of results to keep per target
  payload-size: 56 # message size for ICMP Echo Requests

